--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/ItemStacker
build-by-default: true
branches:
- master
projects:
  ItemStacker:
    path: ""
    icon: "icon.png" 
    libs:
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint: false
...
